import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const PLAYERS = [
  { name: "Messi",   href: "/"        },
  { name: "Ronaldo", href: "/ronaldo" },
];

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <style>{`
          .nav-link {
            font-size: 13px; font-weight: 600; color: #4a5568;
            padding: 6px 14px; border-radius: 8px; text-decoration: none;
            transition: background 0.12s, color 0.12s;
          }
          .nav-link:hover { background: #f4f5f7; color: #1a202c; }
        `}</style>
        <nav style={{
          position: "fixed", top: 0, left: 0, right: 0, zIndex: 1000,
          background: "rgba(255,255,255,0.90)", backdropFilter: "blur(10px)",
          borderBottom: "1px solid #e8eaed",
          display: "flex", alignItems: "center", gap: 4,
          padding: "0 24px", height: 48,
          fontFamily: "'Inter','Helvetica Neue',sans-serif",
        }}>
          <span style={{ fontSize: 11, fontWeight: 700, color: "#b0bac8", letterSpacing: 2, marginRight: 12 }}>
            GOAL ANATOMY
          </span>
          {PLAYERS.map(p => (
            <Link key={p.href} href={p.href} className="nav-link">
              {p.name}
            </Link>
          ))}
        </nav>
        <div style={{ paddingTop: 48 }}>{children}</div>
      </body>
    </html>
  );
}
